project:
  type: website
  output-dir: docs
  # resources:
  #   - shinylive-sw.js
  
website:  
  repo-url: https://github.com/falkcarl/ANOVAvar
  repo-actions: [issue]
  title: "ANOVA variability"

